using System;
using System.Data;
using System.Data.SqlClient;
using System.Linq;
using System.Web.Mvc;
using SchoolDesk.Infrastructure;
using SchoolDesk.Models;
namespace SchoolDesk.Controllers {
 public class SchoolController:Controller {
  const int Size=20;
  ActionResult Listing(string title,string description,string query,int page,string q,params SqlParameter[] extra){page=Math.Max(1,Math.Min(page,10000));q=(q??"").Trim();if(q.Length>100)q=q.Substring(0,100);var ps=extra.Concat(new[]{Db.P("@viewer",Auth.Id),Db.P("@search","%"+q+"%"),Db.P("@skip",(page-1)*Size),Db.P("@take",Size+1)}).ToArray();var rows=Db.Query(query,ps);bool more=rows.Rows.Count>Size;if(more)rows.Rows.RemoveAt(Size);return View("Table",new TablePage{Title=title,Description=description,Rows=rows,Page=page,Search=q,HasNext=more});}
  void Choices(){ViewBag.ClassOptions=Db.Query("SELECT Id,Name+' / '+Section Label FROM Classes ORDER BY Name,Section");ViewBag.ParentOptions=Db.Query("SELECT Id,FullName Label FROM Users WHERE Role='Parent' AND IsActive=1 ORDER BY FullName");ViewBag.StudentUsers=Db.Query("SELECT Id,FullName Label FROM Users WHERE Role='Student' AND IsActive=1 ORDER BY FullName");}
  public ActionResult Students(string q="",int page=1){return Listing("Students","Admissions and student records",@"SELECT s.Id,s.AdmissionNumber,s.FullName,c.Name+' / '+c.Section Class,s.GuardianName,s.GuardianPhone FROM Students s JOIN Classes c ON c.Id=s.ClassId WHERE s.IsActive=1 AND (s.FullName LIKE @search OR s.AdmissionNumber LIKE @search) AND "+Auth.StudentScope+" ORDER BY s.Id DESC OFFSET @skip ROWS FETCH NEXT @take ROWS ONLY",page,q);}
  [RoleAuthorize(Roles="Admin"),HttpGet]public ActionResult Student(int? id){Choices();if(!id.HasValue)return View(new StudentForm{BirthDate=DateTime.Today.AddYears(-10)});var t=Db.Query("SELECT * FROM Students WHERE Id=@id AND IsActive=1",Db.P("@id",id));if(t.Rows.Count==0)return HttpNotFound();var r=t.Rows[0];return View(new StudentForm{Id=(int)r["Id"],FullName=(string)r["FullName"],AdmissionNumber=(string)r["AdmissionNumber"],BirthDate=(DateTime)r["BirthDate"],ClassId=(int)r["ClassId"],GuardianName=r["GuardianName"] as string,GuardianPhone=r["GuardianPhone"] as string,ParentUserId=r["ParentUserId"] as int?,UserId=r["UserId"] as int?});}
  [RoleAuthorize(Roles="Admin"),HttpPost,ValidateAntiForgeryToken]public ActionResult Student(StudentForm f){Choices();if(f.BirthDate>DateTime.Today||f.BirthDate<DateTime.Today.AddYears(-100))ModelState.AddModelError("BirthDate","Enter a valid date of birth.");if(Convert.ToInt32(Db.Scalar("SELECT COUNT(*) FROM Classes WHERE Id=@c",Db.P("@c",f.ClassId)))!=1)ModelState.AddModelError("ClassId","Select an existing class.");foreach(var pair in new[]{Tuple.Create(f.ParentUserId,"Parent"),Tuple.Create(f.UserId,"Student")})if(pair.Item1.HasValue&&Convert.ToInt32(Db.Scalar("SELECT COUNT(*) FROM Users WHERE Id=@id AND Role=@r AND IsActive=1",Db.P("@id",pair.Item1),Db.P("@r",pair.Item2)))!=1)ModelState.AddModelError("","Linked account has an invalid role.");if(!ModelState.IsValid)return View(f);try{var ps=new[]{Db.P("@id",f.Id),Db.P("@a",f.AdmissionNumber.Trim()),Db.P("@n",f.FullName.Trim()),Db.P("@b",f.BirthDate),Db.P("@c",f.ClassId),Db.P("@g",f.GuardianName),Db.P("@p",f.GuardianPhone),Db.P("@parent",f.ParentUserId),Db.P("@user",f.UserId)};if(f.Id==0)Db.Execute("INSERT Students(AdmissionNumber,FullName,BirthDate,ClassId,GuardianName,GuardianPhone,ParentUserId,UserId) VALUES(@a,@n,@b,@c,@g,@p,@parent,@user)",ps);else if(Db.Execute("UPDATE Students SET AdmissionNumber=@a,FullName=@n,BirthDate=@b,ClassId=@c,GuardianName=@g,GuardianPhone=@p,ParentUserId=@parent,UserId=@user WHERE Id=@id AND IsActive=1",ps)!=1)return HttpNotFound();Db.Audit(Auth.Id,f.Id==0?"Create":"Update","Student",f.Id==0?(int?)null:f.Id);TempData["Success"]="Student saved.";return RedirectToAction("Students");}catch(SqlException e){if(e.Number!=2601&&e.Number!=2627)throw;ModelState.AddModelError("","Admission number or linked student account is already in use.");return View(f);}}
  [RoleAuthorize(Roles="Admin"),HttpPost,ValidateAntiForgeryToken]public ActionResult ArchiveStudent(int id){if(Db.Execute("UPDATE Students SET IsActive=0 WHERE Id=@id AND IsActive=1",Db.P("@id",id))!=1)return HttpNotFound();Db.Audit(Auth.Id,"Archive","Student",id);TempData["Success"]="Student archived; historic records preserved.";return RedirectToAction("Students");}
  [RoleAuthorize(Roles="Admin,Teacher")]public ActionResult Classes(){ViewBag.Rows=Db.Query("SELECT c.Id,c.Name,c.Section,u.FullName Teacher,(SELECT COUNT(*) FROM Students WHERE ClassId=c.Id AND IsActive=1) Students FROM Classes c JOIN Users u ON u.Id=c.TeacherId WHERE @admin=1 OR c.TeacherId=@u ORDER BY c.Name",Db.P("@admin",User.IsInRole("Admin")),Db.P("@u",Auth.Id));ViewBag.Teachers=Db.Query("SELECT Id,FullName Label FROM Users WHERE Role='Teacher' AND IsActive=1");return View(new ClassForm());}
  [RoleAuthorize(Roles="Admin"),HttpPost,ValidateAntiForgeryToken]public ActionResult CreateClass(ClassForm f){if(Convert.ToInt32(Db.Scalar("SELECT COUNT(*) FROM Users WHERE Id=@u AND Role='Teacher' AND IsActive=1",Db.P("@u",f.TeacherId)))!=1)ModelState.AddModelError("TeacherId","Select an active teacher.");if(!ModelState.IsValid){TempData["Error"]="Enter valid class details and an active teacher.";return RedirectToAction("Classes");}try{Db.Execute("INSERT Classes(Name,Section,TeacherId) VALUES(@n,@s,@t)",Db.P("@n",f.Name.Trim()),Db.P("@s",f.Section.Trim()),Db.P("@t",f.TeacherId));Db.Audit(Auth.Id,"Create","Class");TempData["Success"]="Class created.";}catch(SqlException e){if(e.Number!=2601&&e.Number!=2627)throw;TempData["Error"]="Class and section already exist.";}return RedirectToAction("Classes");}
  [RoleAuthorize(Roles="Admin"),HttpPost,ValidateAntiForgeryToken]public ActionResult AssignTeacher(int id,int teacherId){if(Convert.ToInt32(Db.Scalar("SELECT COUNT(*) FROM Users WHERE Id=@t AND Role='Teacher' AND IsActive=1",Db.P("@t",teacherId)))!=1)return new HttpStatusCodeResult(400);if(Db.Execute("UPDATE Classes SET TeacherId=@t WHERE Id=@c",Db.P("@t",teacherId),Db.P("@c",id))!=1)return HttpNotFound();Db.Audit(Auth.Id,"Assign teacher","Class",id);return RedirectToAction("Classes");}
  [RoleAuthorize(Roles="Admin")]public ActionResult Users(){ViewBag.Rows=Db.Query("SELECT Id,FullName,Email,Role,IsActive FROM Users ORDER BY Id");return View(new UserForm());}
  [RoleAuthorize(Roles="Admin"),HttpPost,ValidateAntiForgeryToken]public ActionResult CreateUser(UserForm f){if(!new[]{"Admin","Teacher","Accountant","Parent","Student"}.Contains(f.Role))ModelState.AddModelError("Role","Choose a valid role.");if(!ModelState.IsValid){TempData["Error"]="Enter a valid name, email, role and password (12–128 characters).";return RedirectToAction("Users");}try{Db.Execute("INSERT Users(FullName,Email,PasswordHash,Role) VALUES(@n,@e,@p,@r)",Db.P("@n",f.FullName.Trim()),Db.P("@e",f.Email.Trim().ToLowerInvariant()),Db.P("@p",Passwords.Hash(f.Password)),Db.P("@r",f.Role));Db.Audit(Auth.Id,"Create","User");TempData["Success"]="User created.";}catch(SqlException e){if(e.Number!=2601&&e.Number!=2627)throw;TempData["Error"]="Email already exists.";}return RedirectToAction("Users");}
  [RoleAuthorize(Roles="Admin"),HttpPost,ValidateAntiForgeryToken]public ActionResult SetUserActive(int id,bool active){if(id==Auth.Id){TempData["Error"]="You cannot disable your own account.";return RedirectToAction("Users");}if(Db.Execute("UPDATE Users SET IsActive=@a,SecurityVersion=SecurityVersion+1 WHERE Id=@u",Db.P("@a",active),Db.P("@u",id))!=1)return HttpNotFound();Db.Audit(Auth.Id,active?"Enable":"Disable","User",id);return RedirectToAction("Users");}
  [RoleAuthorize(Roles="Admin,Teacher"),HttpGet]public ActionResult Attendance(int? classId,DateTime? day){ViewBag.Classes=Db.Query("SELECT Id,Name+' / '+Section Label FROM Classes WHERE @admin=1 OR TeacherId=@u",Db.P("@admin",User.IsInRole("Admin")),Db.P("@u",Auth.Id));var date=(day??DateTime.Today).Date;ViewBag.Day=date;ViewBag.ClassId=classId;if(classId.HasValue&&!Auth.CanClass(classId.Value))return new HttpStatusCodeResult(403);ViewBag.Rows=classId.HasValue?Db.Query("SELECT s.Id,s.AdmissionNumber,s.FullName,COALESCE(a.Status,'Present') Status FROM Students s LEFT JOIN Attendance a ON a.StudentId=s.Id AND a.Day=@day WHERE s.ClassId=@c AND s.IsActive=1 ORDER BY s.FullName",Db.P("@day",date),Db.P("@c",classId)):new DataTable();return View();}
  [RoleAuthorize(Roles="Admin,Teacher"),HttpPost,ValidateAntiForgeryToken]public ActionResult SaveAttendance(int classId,DateTime day,int[] studentIds,string[] statuses){if(!Auth.CanClass(classId))return new HttpStatusCodeResult(403);if(day.Date>DateTime.Today||day.Date<DateTime.Today.AddYears(-2)||studentIds==null||statuses==null||studentIds.Length!=statuses.Length||studentIds.Length>500||studentIds.Distinct().Count()!=studentIds.Length||statuses.Any(s=>!new[]{"Present","Absent","Late","Excused"}.Contains(s)))return new HttpStatusCodeResult(400);using(var c=Db.Open())using(var tx=c.BeginTransaction(IsolationLevel.Serializable)){for(int i=0;i<studentIds.Length;i++){using(var cmd=new SqlCommand(@"IF NOT EXISTS(SELECT 1 FROM Students WHERE Id=@s AND ClassId=@c AND IsActive=1) THROW 50001,'Invalid student',1; UPDATE Attendance SET Status=@status,RecordedBy=@u WHERE StudentId=@s AND Day=@d; IF @@ROWCOUNT=0 INSERT Attendance(StudentId,Day,Status,RecordedBy) VALUES(@s,@d,@status,@u);",c,tx)){cmd.Parameters.AddRange(new[]{Db.P("@s",studentIds[i]),Db.P("@c",classId),Db.P("@status",statuses[i]),Db.P("@u",Auth.Id),Db.P("@d",day.Date)});cmd.ExecuteNonQuery();}}tx.Commit();}Db.Audit(Auth.Id,"Record attendance","Class",classId);TempData["Success"]="Attendance saved.";return RedirectToAction("Attendance",new{classId,day=day.ToString("yyyy-MM-dd")});}
  [RoleAuthorize(Roles="Admin,Accountant,Parent,Student")]public ActionResult Fees(string q="",int page=1){return Listing("Fees","Invoices, payments and outstanding balances",@"SELECT i.Id,s.FullName Student,i.Description,i.Amount,COALESCE(p.Paid,0) Paid,i.Amount-COALESCE(p.Paid,0) Balance,i.DueDate FROM Invoices i JOIN Students s ON s.Id=i.StudentId OUTER APPLY(SELECT SUM(Amount) Paid FROM Payments WHERE InvoiceId=i.Id)p WHERE s.FullName LIKE @search AND "+Auth.StudentScope+" ORDER BY i.Id DESC OFFSET @skip ROWS FETCH NEXT @take ROWS ONLY",page,q);}
  [RoleAuthorize(Roles="Admin,Accountant"),HttpGet]public ActionResult Invoice(){ViewBag.Students=Db.Query("SELECT Id,FullName+' / '+AdmissionNumber Label FROM Students WHERE IsActive=1 ORDER BY FullName");return View(new InvoiceForm{DueDate=DateTime.Today.AddDays(14)});}
  [RoleAuthorize(Roles="Admin,Accountant"),HttpPost,ValidateAntiForgeryToken]public ActionResult Invoice(InvoiceForm f){ViewBag.Students=Db.Query("SELECT Id,FullName+' / '+AdmissionNumber Label FROM Students WHERE IsActive=1 ORDER BY FullName");if(f.DueDate.Year<2000||f.DueDate.Year>2100)ModelState.AddModelError("DueDate","Enter a valid due date.");if(Convert.ToInt32(Db.Scalar("SELECT COUNT(*) FROM Students WHERE Id=@s AND IsActive=1",Db.P("@s",f.StudentId)))!=1)ModelState.AddModelError("StudentId","Choose an active student.");if(!ModelState.IsValid)return View(f);Db.Execute("INSERT Invoices(StudentId,Description,Amount,DueDate,CreatedBy) VALUES(@s,@d,@a,@due,@u)",Db.P("@s",f.StudentId),Db.P("@d",f.Description),Db.P("@a",f.Amount),Db.P("@due",f.DueDate),Db.P("@u",Auth.Id));Db.Audit(Auth.Id,"Create","Invoice");TempData["Success"]="Invoice created.";return RedirectToAction("Fees");}
  [RoleAuthorize(Roles="Admin,Accountant,Parent,Student")]public ActionResult Receipt(int id){var t=Db.Query("SELECT i.*,s.FullName,s.AdmissionNumber,COALESCE(p.Paid,0) Paid,i.Amount-COALESCE(p.Paid,0) Balance FROM Invoices i JOIN Students s ON s.Id=i.StudentId OUTER APPLY(SELECT SUM(Amount) Paid FROM Payments WHERE InvoiceId=i.Id)p WHERE i.Id=@id AND "+Auth.StudentScope,Db.P("@id",id),Db.P("@viewer",Auth.Id));if(t.Rows.Count!=1)return HttpNotFound();ViewBag.Invoice=t.Rows[0];ViewBag.Payments=Db.Query("SELECT Reference,Amount,PaidAt FROM Payments WHERE InvoiceId=@id ORDER BY Id",Db.P("@id",id));return View(new PaymentForm{InvoiceId=id});}
  [RoleAuthorize(Roles="Admin,Accountant"),HttpPost,ValidateAntiForgeryToken]public ActionResult Pay(PaymentForm f){if(!ModelState.IsValid){TempData["Error"]="Enter a positive amount and a unique payment reference.";return RedirectToAction("Receipt",new{id=f.InvoiceId});}try{using(var c=Db.Open())using(var tx=c.BeginTransaction(IsolationLevel.Serializable)){using(var cmd=new SqlCommand(@"DECLARE @total decimal(12,2); SELECT @total=Amount FROM Invoices WITH(UPDLOCK,HOLDLOCK) WHERE Id=@id; IF @total IS NULL THROW 50002,'Invoice missing',1; DECLARE @paid decimal(12,2)=(SELECT COALESCE(SUM(Amount),0) FROM Payments WHERE InvoiceId=@id); IF @a>@total-@paid THROW 50003,'Payment exceeds balance',1; INSERT Payments(InvoiceId,Amount,Reference,RecordedBy) VALUES(@id,@a,@r,@u); INSERT AuditLogs(ActorId,Action,Entity,EntityId) VALUES(@u,'Record payment','Invoice',@id);",c,tx)){cmd.Parameters.AddRange(new[]{Db.P("@id",f.InvoiceId),Db.P("@a",f.Amount),Db.P("@r",f.Reference.Trim()),Db.P("@u",Auth.Id)});cmd.ExecuteNonQuery();}tx.Commit();}TempData["Success"]="Payment recorded.";}catch(SqlException e){if(!new[]{2601,2627,50002,50003}.Contains(e.Number))throw;TempData["Error"]="Payment not saved. Check invoice balance and use a unique reference.";}return RedirectToAction("Receipt",new{id=f.InvoiceId});}
  [RoleAuthorize(Roles="Admin,Teacher")]public ActionResult Exams(){ViewBag.Rows=Db.Query("SELECT e.Id,e.Title,e.Subject,c.Name+' / '+c.Section Class,e.MaxMarks,e.ExamDate FROM Exams e JOIN Classes c ON c.Id=e.ClassId WHERE @admin=1 OR c.TeacherId=@u ORDER BY e.ExamDate DESC",Db.P("@admin",User.IsInRole("Admin")),Db.P("@u",Auth.Id));ViewBag.Classes=Db.Query("SELECT Id,Name+' / '+Section Label FROM Classes WHERE @admin=1 OR TeacherId=@u",Db.P("@admin",User.IsInRole("Admin")),Db.P("@u",Auth.Id));return View(new ExamForm{ExamDate=DateTime.Today,MaxMarks=100});}
  [RoleAuthorize(Roles="Admin,Teacher"),HttpPost,ValidateAntiForgeryToken]public ActionResult CreateExam(ExamForm f){if(!Auth.CanClass(f.ClassId))return new HttpStatusCodeResult(403);if(f.ExamDate.Year<2000||f.ExamDate.Year>2100)ModelState.AddModelError("ExamDate","Invalid date.");if(!ModelState.IsValid){TempData["Error"]="Enter valid exam details.";return RedirectToAction("Exams");}Db.Execute("INSERT Exams(ClassId,Title,Subject,MaxMarks,ExamDate,CreatedBy) VALUES(@c,@t,@s,@m,@d,@u)",Db.P("@c",f.ClassId),Db.P("@t",f.Title),Db.P("@s",f.Subject),Db.P("@m",f.MaxMarks),Db.P("@d",f.ExamDate),Db.P("@u",Auth.Id));Db.Audit(Auth.Id,"Create","Exam");return RedirectToAction("Exams");}
  [RoleAuthorize(Roles="Admin,Teacher"),HttpGet]public ActionResult Marks(int id){var e=Db.Query("SELECT * FROM Exams WHERE Id=@id",Db.P("@id",id));if(e.Rows.Count!=1)return HttpNotFound();var row=e.Rows[0];if(!Auth.CanClass((int)row["ClassId"]))return new HttpStatusCodeResult(403);ViewBag.Exam=row;ViewBag.Rows=Db.Query("SELECT s.Id,s.FullName,r.Marks FROM Students s LEFT JOIN Results r ON r.StudentId=s.Id AND r.ExamId=@e WHERE s.ClassId=@c AND s.IsActive=1 ORDER BY s.FullName",Db.P("@e",id),Db.P("@c",row["ClassId"]));return View();}
  [RoleAuthorize(Roles="Admin,Teacher"),HttpPost,ValidateAntiForgeryToken]public ActionResult SaveMarks(int examId,int[] studentIds,decimal[] marks){var e=Db.Query("SELECT * FROM Exams WHERE Id=@id",Db.P("@id",examId));if(e.Rows.Count!=1)return HttpNotFound();var row=e.Rows[0];if(!Auth.CanClass((int)row["ClassId"]))return new HttpStatusCodeResult(403);if(!ModelState.IsValid||studentIds==null||marks==null||studentIds.Length!=marks.Length||studentIds.Length>500||studentIds.Distinct().Count()!=studentIds.Length||marks.Any(m=>m<0||m>(int)row["MaxMarks"]))return new HttpStatusCodeResult(400);using(var c=Db.Open())using(var tx=c.BeginTransaction(IsolationLevel.Serializable)){for(int i=0;i<studentIds.Length;i++){using(var cmd=new SqlCommand(@"IF NOT EXISTS(SELECT 1 FROM Students WHERE Id=@s AND ClassId=@c AND IsActive=1) THROW 50001,'Invalid student',1; UPDATE Results SET Marks=@m,RecordedBy=@u WHERE ExamId=@e AND StudentId=@s; IF @@ROWCOUNT=0 INSERT Results(ExamId,StudentId,Marks,RecordedBy) VALUES(@e,@s,@m,@u);",c,tx)){cmd.Parameters.AddRange(new[]{Db.P("@s",studentIds[i]),Db.P("@c",row["ClassId"]),Db.P("@m",marks[i]),Db.P("@u",Auth.Id),Db.P("@e",examId)});cmd.ExecuteNonQuery();}}tx.Commit();}Db.Audit(Auth.Id,"Record marks","Exam",examId);TempData["Success"]="Marks saved.";return RedirectToAction("Marks",new{id=examId});}
  [RoleAuthorize(Roles="Admin,Teacher,Parent,Student")]public ActionResult Reports(string q="",int page=1){return Listing("Results & reports","Exam results visible within your assigned access",@"SELECT s.FullName Student,c.Name+' / '+c.Section Class,e.Title,e.Subject,r.Marks,e.MaxMarks,CAST(100.0*r.Marks/e.MaxMarks AS decimal(5,2)) Percentage FROM Results r JOIN Students s ON s.Id=r.StudentId JOIN Classes c ON c.Id=s.ClassId JOIN Exams e ON e.Id=r.ExamId WHERE s.FullName LIKE @search AND "+Auth.StudentScope+" ORDER BY e.ExamDate DESC,r.Id DESC OFFSET @skip ROWS FETCH NEXT @take ROWS ONLY",page,q);}
  public ActionResult AttendanceHistory(string q="",int page=1){return Listing("Attendance history","Recorded attendance within your assigned access",@"SELECT s.FullName Student,c.Name+' / '+c.Section Class,a.Day,a.Status FROM Attendance a JOIN Students s ON s.Id=a.StudentId JOIN Classes c ON c.Id=s.ClassId WHERE s.FullName LIKE @search AND "+Auth.StudentScope+" ORDER BY a.Day DESC,a.Id DESC OFFSET @skip ROWS FETCH NEXT @take ROWS ONLY",page,q);}
  [RoleAuthorize(Roles="Admin")]public ActionResult Audit(string q="",int page=1){return Listing("Activity log","Administrative and financial changes",@"SELECT a.Id,u.FullName Actor,a.Action,a.Entity,a.EntityId,a.OccurredAt FROM AuditLogs a JOIN Users u ON u.Id=a.ActorId WHERE (a.Action LIKE @search OR a.Entity LIKE @search) ORDER BY a.Id DESC OFFSET @skip ROWS FETCH NEXT @take ROWS ONLY",page,q);}
 }
}
