<Project Sdk="Microsoft.NET.Sdk">
 <PropertyGroup><TargetFramework>net48</TargetFramework><LangVersion>7.3</LangVersion><OutputType>Library</OutputType><RootNamespace>SchoolDesk</RootNamespace><AssemblyName>SchoolDesk</AssemblyName><OutputPath>bin\</OutputPath><AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath><CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies><AutoGenerateBindingRedirects>true</AutoGenerateBindingRedirects><GenerateBindingRedirectsOutputType>true</GenerateBindingRedirectsOutputType></PropertyGroup>
 <ItemGroup><Reference Include="System.Web"/><Reference Include="System.Configuration"/><Reference Include="System.Data"/><Reference Include="System.Runtime.Caching"/><Reference Include="System.ComponentModel.DataAnnotations"/></ItemGroup>
 <ItemGroup><PackageReference Include="Microsoft.NETFramework.ReferenceAssemblies" Version="1.0.3" PrivateAssets="all"/><PackageReference Include="Microsoft.AspNet.Mvc" Version="5.3.0"/><PackageReference Include="Microsoft.AspNet.Razor" Version="3.3.0"/><PackageReference Include="Microsoft.AspNet.WebPages" Version="3.3.0"/><PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.23.0"/></ItemGroup>
</Project>
